version: "3.9"
   
services:
  db:
    image: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data:z
    restart: always
    environment:
      - POSTGRES_DB=simpledoc
      - POSTGRES_USER=simpledoc
      - POSTGRES_PASSWORD=admin
  backend:
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    restart: always
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db